# k8s/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - prod-config.properties
  name: solmar-config-prod

# Genera el Secret leyendo el archivo .env (Kustomize lo codifica por ti)
secretGenerator:
- envs:
  - prod-secrets.env
  name: solmar-secrets-prod

# Aplica los patches de imagen y r√©plicas
patchesStrategicMerge:
- replicas.yaml

# Aplica el parche de variables de entorno a TODOS los Deployments
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - configMapRef:
            name: solmar-config-prod
        - secretRef:
            name: solmar-secrets-prod
  target:
    kind: Deployment
resources:
- ../../base
images:
- name: diurvan/solmar-backend-authservice
  newName: diurvan/solmar-backend-authservice
  newTag: ef3bba2
- name: diurvan/solmar-backend-catalogservice
  newName: diurvan/solmar-backend-catalogservice
  newTag: ef3bba2
- name: diurvan/solmar-backend-finanzasservice
  newName: diurvan/solmar-backend-finanzasservice
  newTag: ef3bba2
- name: diurvan/solmar-backend-notificationsservice
  newName: diurvan/solmar-backend-notificationsservice
  newTag: ef3bba2
- name: diurvan/solmar-backend-reservationsservice
  newName: diurvan/solmar-backend-reservationsservice
  newTag: ef3bba2
- name: diurvan/solmar-backend-yarpproxy
  newName: diurvan/solmar-backend-yarpproxy
  newTag: ef3bba2
- name: diurvan/solmar-backend-mediaservice
  newName: diurvan/solmar-backend-mediaservice
  newTag: ef3bba2
