apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarp-proxy
  template:
    metadata:
      labels:
        app: yarp-proxy
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yarp-proxy-service
spec:
  type: NodePort
  selector:
    app: yarp-proxy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30577
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: auth-service
        image: diurvan/solmar-backend # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations-service
  template:
    metadata:
      labels:
        app: reservations-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: reservations-service
        image: diurvan/solmar-backend # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reservations-service
spec:
  selector:
    app: reservations-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finanzas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finanzas-service
  template:
    metadata:
      labels:
        app: finanzas-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: finanzas-service
        image: diurvan/solmar-backend # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: finanzas-service
spec:
  selector:
    app: finanzas-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: notifications-service
        image: diurvan/solmar-backend # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: catalog-service
        image: diurvan/solmar-backend # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - port: 8080
    targetPort: 8080
