apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarp-proxy
  template:
    metadata:
      labels:
        app: yarp-proxy
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: yarp-proxy
        image: diurvan/solmar-backend-yarpproxy # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yarp-proxy-service
spec:
  type: NodePort
  selector:
    app: yarp-proxy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30577
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: auth-service
        image: diurvan/solmar-backend-authservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations-service
  template:
    metadata:
      labels:
        app: reservations-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: reservations-service
        image: diurvan/solmar-backend-reservationsservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reservations-service
spec:
  selector:
    app: reservations-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finanzas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finanzas-service
  template:
    metadata:
      labels:
        app: finanzas-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: finanzas-service
        image: diurvan/solmar-backend-finanzasservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: finanzas-service
spec:
  selector:
    app: finanzas-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: notifications-service
        image: diurvan/solmar-backend-notificationsservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: solmar-env-vars
        env:
        - name: Firebase__ServiceAccountKeyPath
          value: "/etc/firebase/firebase-adminsdk.json"
        volumeMounts:
        - name: firebase-secret-volume
          mountPath: "/etc/firebase"
          readOnly: true
      volumes:
      - name: firebase-secret-volume
        secret:
          secretName: firebase-admin-sdk
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: catalog-service
        image: diurvan/solmar-backend-catalogservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberships-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberships-service
  template:
    metadata:
      labels:
        app: memberships-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: memberships-service
        image: diurvan/solmar-backend-membershipsservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: memberships-service
spec:
  selector:
    app: memberships-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaservice
  template:
    metadata:
      labels:
        app: mediaservice
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: mediaservice
        image: diurvan/solmar-backend-mediaservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mediaservice
spec:
  selector:
    app: mediaservice
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localizationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localizationservice
  template:
    metadata:
      labels:
        app: localizationservice
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: localizationservice
        image: diurvan/solmar-backend-localizationservice # Tag will be added by Kustomize
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: localizationservice
spec:
  selector:
    app: localizationservice
  ports:
  - port: 8080
    targetPort: 8080