apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
      - name: auth-service
        image: diurvan/solmar-backend-authservice:6af71f8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  template:
    spec:
      containers:
      - name: reservations-service
        image: diurvan/solmar-backend-reservationsservice:6af71f8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finanzas-service
spec:
  template:
    spec:
      containers:
      - name: finanzas-service
        image: diurvan/solmar-backend-finanzasservice:6af71f8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  template:
    spec:
      containers:
      - name: notifications-service
        image: diurvan/solmar-backend-notificationsservice:6af71f8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
spec:
  template:
    spec:
      containers:
      - name: yarp-proxy
        image: diurvan/solmar-backend-yarpproxy:6af71f8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
      - name: catalog-service
        image: diurvan/solmar-backend-catalogservice:6af71f8
---
